### PR TITLE
Sparrow Guide using Bitcoin Core RPC makeover

### PR DESCRIPTION
**Pull request by gStart9**

### CODE REVIEW

**Comment by gStart9** [comment]
The latest can be seen here if you would like to view it:

https://github.com/Start9Labs/bitcoind-wrapper/blob/8eba575b67454c8e11ccf5392ad82d818a783167/docs/integrations/sparrow/guide.md

**Review by kn0wmad — APPROVED** [review]

**Comment by chrisguida** [comment]
What in the world is "Cormorant"?

**Comment by gStart9** [comment]
The new sparrow [release notes](https://github.com/sparrowwallet/sparrow/releases/tag/1.7.2) provide a clue:
* Add Taproot support on Bitcoin Core using the **new Cormorant library** utilizing descriptor wallets (requires Bitcoin Core v24 or later)
* Add support for private key sweeping using Bitcoin Core with Cormorant (requires Bitcoin Core v24 or later)

Is this something you wrote, @craigraw?  Or where might it live?

**Comment by craigraw** [comment]
Correct, I wrote Cormorant as an upgrade to BWT (still included in Sparrow) to leverage Core descriptor wallets. It is effectively the same thing as EPS/BWT, but uses descriptor wallets (with ranged descriptors, not addresses) as the index/persistence layer. It's also going to much easier to maintain and improve over time - BWT has not seen any development in almost a year.

**Pull request merged**
