### PR TITLE
Changes to Sparrow Bitcoin RPC instructions with Tor

### PR DESCRIPTION
**Pull request by gStart9**
To work around sparrow bugs

### CODE REVIEW

**Comment by chrisguida** [comment]
This should not be necessary. Just select "Use Proxy" and point it at your Tor proxy:

Screen Shot 2022-07-22 at 9 35 51 AM

**Comment by gStart9** [comment]
I completely agree that "This should not be necessary", however, it seems it is if there is already a tor proxy running on 127.0.0.1:9050 - I tested on 2 of my Linux distros - neither Sparrow install would work unless I actually shut down tor via sudo systemctl stop tor

I also had a support issue with someone on MacOS where it would not work (same symptoms) until I had her disable "Use Proxy", then the tor proxy package built into Sparrow launched its own tor (4.3.2 iirc), built a circuit, and connected to electrum just fine.  @chrisguida was this screenshot you just took from your own MacOS install of Sparrow?  And it's working like that?

**Comment by chrisguida** [comment]
Yes, this is from MacOS, and yes, it works just fine. It sounds like there may be a bug in Sparrow's Linux implementation, have we filed a bug with them? Would be great to link to that issue in our integration docs so that users can see exactly what problem we're working around, and when the issue is officially closed everyone will know the workaround is no longer necessary.

**Comment by kn0wmad** [comment]
This is very bizarre to me.  This was tested good, and yet when opening my Sparrow (Linux) to verify, I ran into the same problem.  There has not been a Sparrow update (or rather I have not downloaded it), so I cannot understand how this came to be.  I'm concerned about having users flip off their native Tor daemon, as they will likely need it for other services and that could generate support load

**Comment by gStart9** [comment]
Issue created: https://github.com/sparrowwallet/sparrow/issues/634

**Comment by chrisguida** [comment]
@gStart9 would you mind referencing this upstream issue in our docs? That way users can directly reference the problem without coming to us

**Pull request closed without merging**
