### PR TITLE
remove warning about abusing your node by increasing threads

### PR DESCRIPTION
**Pull request by BitcoinMechanic**

### CODE REVIEW

**Comment by kn0wmad** [comment]
This was available for testing in its final form for the last week and the RPC changes were made a month ago.  Please try to get copy changes in before release tags are being cut in the future

**Comment by chrisguida** [comment]
Why was this closed? We can still merge this and get it in next release...

**Comment by kn0wmad** [comment]
I changed the sentence in question already

**Comment by kn0wmad** [comment]
I don't know where you see the date, but the commit was before my comment.  I wouldn't say something was done if it wasn't.  I closed only because the change had already been made.

**Comment by chrisguida** [comment]
Ok, just be sure to link to the conflicting change next time

**Pull request closed without merging**
